DROP TABLE anime_producer_join;
DROP TABLE anime_licensor_join ;
DROP TABLE anime_studio_join;
DROP TABLE anime_producer;
DROP TABLE anime_licensor;
DROP TABLE anime_studio;
DROP TABLE anime_genre_join;
DROP TABLE anime_theme_join;
DROP TABLE anime_demographic_join;
DROP TABLE anime;
DROP TABLE anime_series;
DROP TABLE anime_genre;
DROP TABLE anime_theme;
DROP TYPE anime_type;
DROP TYPE anime_status;
DROP TYPE anime_rating;
DROP TYPE source_material;
DROP TYPE anime_demographic;