export enum SourceMaterial {
    ORIGINAL = "Original",
    MANGA = "Manga",
    LIGHT_NOVEL = "Light novel",
    GAME = "Game",
    VISUAL_NOVEL = "Visual novel",
    YONKOMA = "Yonkoma",
    NOVEL = "Novel",
    OTHER = "Other",
    UNKNOWN = "Unknown",
    PICTURE_BOOK = "Picture book",
    WEB_MANGA = "Web manga",
    MUSIC = "Music",
    RADIO = "Radio",
    BOOK = "Book",
    MIXED_MEDIA = "Mixed media",
    CARD_GAME = "Card game",
    WEB_NOVEL = "Web novel",
}
