export enum SourceMaterial {
    BOOK = "Book",
    CARD_GAME = "Card game",
    GAME = "Game",
    LIGHT_NOVEL = "Light novel",
    MANGA = "Manga",
    MIXED_MEDIA = "Mixed media",
    MUSIC = "Music",
    NOVEL = "Novel",
    ORIGINAL = "Original",
    OTHER = "Other",
    PICTURE_BOOK = "Picture book",
    RADIO = "Radio",
    UNKNOWN = "Unknown",
    VISUAL_NOVEL = "Visual novel",
    WEB_MANGA = "Web manga",
    WEB_NOVEL = "Web novel",
    YONKOMA = "Yonkoma",
}
